// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbpipqltnkhnchhjmkrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicGlwcWx0bmtobmNoaGpta3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTA3MDAsImV4cCI6MjA1ODQ2NjcwMH0.YnhfMPi-UxHQEnQISZX68i2ZaOk0qGDU8AiIpl43VfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);